//
// Created by Dysprosium on 2023/6/18.
//

#ifndef GREAT_BUCT_COMPILER_SRC_INCLUDE_SEMANTICS_BINARY_AST_H_
#define GREAT_BUCT_COMPILER_SRC_INCLUDE_SEMANTICS_BINARY_AST_H_

class binary_ast {

};

#endif //GREAT_BUCT_COMPILER_SRC_INCLUDE_SEMANTICS_BINARY_AST_H_
